name: Compile using numba
on: [push]
jobs:
  aws_compile:
    runs-on: ubuntu-latest
    container:
      image: public.ecr.aws/sam/emulation-python3.8:latest
    name: Compile for python version ${{ matrix.python-version }} on ${{ matrix.os }}
    steps:
      - run: sudo yum install tar
      - uses: actions/checkout@v2
      - run: pip install -r requirements.txt
      - run: python kernels.py
      - uses: actions/upload-artifact@v2
        with: 
          name: compiled_modules
          path: pldist.*.*
